### ISSUE TITLE
response.records not working with rails 3.0.x

### ISSUE THREAD

**Issue by tmcabee** [elastic/elasticsearch-rails#73]
I was investigating using this gem in rails 3.0.20.  It bundle installs fine, and I was able to perform a search of my data.  However, when attempting to call the "records" method on the search response, I see the following error:

NoMethodError: undefined method `exec_queries' for #<ActiveRecord::Relation:0x00000005715db8>
from /home/tworker/work/ove-ruby/vendor/bundle/ruby/1.9.1/gems/activerecord-3.0.20/lib/active_record/relation.rb:374:in`method_missing'

It looks like the "exec_queries" method is only available in rails 3.2.x.  There is a "to_a" method available in 3.0.x which is very similar, but simply changing the gem to call that gets into a recursion issue.  Is there a simple fix you can think of to allow this gem to be used in 3.0?  I'll continue to investigate as well...thank you.
