### ISSUE TITLE
Regression in v6.1.0: 'method_missing': undefined method `model_name' for [PROXY] 

### ISSUE THREAD

**Issue by shoe** [elastic/elasticsearch-rails#901]
The following error appears when upgrading from 6.0.0 to 6.1.0, and disappears when reverting to 6.0.0.

```
/.rvm/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/proxy.rb:96:in `method_missing': undefined method `model_name' for [PROXY] ContactSearchIndex:Elasticsearch::Model::Proxy::ClassMethodsProxy (NoMethodError)
	from /.rvm/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/naming.rb:96:in `default_index_name'
	from /.rvm/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/naming.rb:92:in `implicit'
	from /.rvm/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/naming.rb:39:in `index_name'
	from /.rvm/gems/elasticsearch-model-6.1.0/lib/elasticsearch/model/indexing.rb:225:in `create_index!'
```

**Comment by estolfo** [comment]
@shoe Thanks for reporting this, I'll have an update soon!

**Comment by estolfo** [comment]
@shoe Can you please provide an example Model that causes this error? I'm unable to reproduce it without more info. Thanks!

**Comment by estolfo** [comment]
Hi @shoe Is there any chance you can provide an example Model that causes this error? Thanks!

**Comment by estolfo** [comment]
Hi @shoe I've been able to reproduce this and are you sure your Model inherits from `ActiveRecord::Base`?

for example:

```ruby
class Testing
  include Elasticsearch::Model
end

> Testing.__elasticsearch__.create_index!
NoMethodError: undefined method `model_name' for [PROXY] Elasticsearch::Model::DynamicIndexNameTest::Testing:Elasticsearch::Model::Proxy::ClassMethodsProxy
from /...elasticsearch-rails/elasticsearch-model/lib/elasticsearch/model/proxy.rb:96:in `method_missing'
```

versus:

```ruby
class TestingWithActiveRecord < ActiveRecord::Base
  include Elasticsearch::Model
end

> TestingWithActiveRecord.__elasticsearch__.create_index!
=> {"acknowledged"=>true, "shards_acknowledged"=>true, "index"=>"testing_with_active_records"}

**Comment by shoe** [comment]
@estolfo Thanks for having a look even without more info.  My situation is a bit complex.  My documents are all modeled by something that inherits from `ActiveRecord::Base` (`ApplicationRecord`).  But there is not a 1:1 mapping between my document classes and my ES indexes and I need to manage each ES index individually, so my ES indexes modeled by plain ruby objects that include (eventually) `Elasticsearch::Model`.

Here is a drastically simplified version of what I described above:
```ruby
require 'elasticsearch/model'

module SearchIndex
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    # these settings will apply to each index
    settings \
      index: {
      number_of_shards: 5,
      number_of_replicas: 1
    },
    analysis: {
      filter: {
        my_edge_ngram_filter: {
          type: 'edgeNGram',
          min_gram: 3,
          max_gram: 17
        }
      },
      analyzer: {
        default: { # Overrides the default index analyzer to use the ngram filter
          type: 'custom',
          tokenizer: 'standard',
          filter: ['lowercase', 'my_edge_ngram_filter']
        },
        default_search: {  # At search time, use this as the default search analyzer
          type: 'standard' # This reuses the standard analyzer.
        }
      }
    }
  end

  class_methods do
    delegate :client, :create_index!, to: :__elasticsearch__
  end

  module ModelBase
    extend ActiveSupport::Concern
    included do
      attr_accessor :expiring
    end
  end
end

class ContactSearchIndex
  include SearchIndex

  class << self
    def index_name
      "contacts-#{ENV["DEPLOY_ENV"]}"
    end

    def document_type
      'contact'
    end
  end

  module Contact
    extend ActiveSupport::Concern
    include SearchIndex::ModelBase
  end
end

class Contact < ApplicationRecord
  include ContactSearchIndex::Contact
end

ContactSearchIndex.create_index!(force: true)
```
